eureka:
  instance:
    instance-id: ${spring.application.name}
    prefer-ip-address: true
server:
  port: 20262
spring:
  application:
    name: pipeline
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    function:
      definition: processProduct;processMessage;processProductDetail;processDbChanges # must be the same - processProduct
    stream:
      bindings:
        processProductDetail-in-0:
          destination: product-detail
          group: monitor-group2
          content-type: application/json
        processProduct-in-0: # must be the same - processProduct
          destination: test-product # topic_name
          group: monitor-group # consumer_group_id
          content-type: application/json
        processMessage-in-0:
          destination: test-topic
        processProductDetail-out-0:
          destination: processed-product-detail
          content-type: application/json
        # CDC Bindings
        processDbChanges-in-0:
          destination: dbserver1.public.products
          group: cdc-group-v3
          consumer:
            use-native-decoding: true
        processDbChanges-out-0:
          destination: processed-cdc-events
          content-type: application/json
      kafka:
        binder:
          brokers: localhost:29092,localhost:29094,localhost:29096
          consumer-properties:
            key.deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
            value.deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
            spring.deserializer.key.delegate.class: io.confluent.kafka.serializers.KafkaAvroDeserializer
            spring.deserializer.value.delegate.class: io.confluent.kafka.serializers.KafkaAvroDeserializer
            schema.registry.url: http://localhost:8081
            specific.avro.reader: false
            auto.offset.reset: latest
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090
      client:
        provider:
          itp-standard:
            issuer-uri: http://localhost:9090
        registration:
          itp-standard:
            provider: itp-standard
            client-id: itp-standard
            client-secret: qwerqwer
            redirect-uri: http://localhost:9999/login/oauth2/code/itp-standard
            authorization-grant-type: client_credentials
            scope:
              - openid # Auto issue access token
              - profile # Get profile
              - email # Get email
# Resilience4J
resilience4j:
  circuitbreaker:
    instances:
      account:
        sliding-window-size: 10
        failure-rate-threshold: 50
        permitted-number-of-calls-in-half-open-state: 2
        wait-duration-in-open-state: 10000
# Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    dev.oudom.pipeline: DEBUG